name: music_player
description: A modern Flutter music player app

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  just_audio: ^0.9.34
  audio_service: ^0.18.7
  riverpod: ^2.1.3
  flutter_riverpod: ^2.1.3
  shimmer: ^2.0.0
  cached_network_image: ^3.2.3
  share_plus: ^6.3.0
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/